#FASE 1: CRIAR O BANCO DE DADOS (SCHEMA OU DATABASE):
#MEU PRIMEIRO BANQUINHO
CREATE SCHEMA EC1_CC1M;

#FASE 2: SELECIONAR O NOVO SCHEMA OU DATABASE PARA USO:
#USANDO MEU BANQUINHO
USE EC1_CC1M;


# FASE 3: CRIANDO AS TABELAS SEM CHAVES ESTRANGEIRAS

#CRIANDO A TABELINHA FORNECEDORES
CREATE TABLE IF NOT EXISTS FORNECEDORES(
#NOMEDOATRIBUTO - TIPO - RESTRIÇÃO DE INTEGRIDADE(OPCIONAL)
FORNEC_COD INT PRIMARY KEY,
FORNEC_NOME VARCHAR(45) NOT NULL,
FORNEC_RUA VARCHAR(45) NOT NULL,
FORNEC_NUMRUA INT,
FORNEC_BAIRRO VARCHAR(45) NOT NULL,
FORNEC_CIDADE VARCHAR(45) NOT NULL,
FORNEC_ESTADO VARCHAR(45) NOT NULL,
FORNEC_PAIS VARCHAR(30) NOT NULL,
FORNEC_CODPOSTAL VARCHAR(10) NOT NULL,
FORNEC_TELEFONE VARCHAR(15) NOT NULL,
FORNEC_CONTATO TEXT NOT NULL
);

INSERT INTO FORNECEDORES (FORNEC_NOME, FORNEC_NUMRUA, FORNEC_BAIRRO)
VALUES ('Labirinto', '365', 'Praia da Costa');
INSERT INTO FORNECEDORES (FORNEC_NOME, FORNEC_NUMRUA, FORNEC_BAIRRO)
VALUES ('laringement', '366', 'itaparica');
INSERT INTO FORNECEDORES (FORNEC_NOME, FORNEC_NUMRUA, FORNEC_BAIRRO)
VALUES ('Larabio', '367', 'Praia da Costa');

#CRIANDO A TABELINHA FILIAIS
CREATE TABLE IF NOT EXISTS FILIAIS(
FILIAL_COD INT PRIMARY KEY,
FILIAL_NOME VARCHAR(45) NOT NULL,
FILIAL_RUA VARCHAR(100) NOT NULL,
FILIAL_NUMRUA INT,
FILIAL_BAIRRO VARCHAR(50) NOT NULL,
FILIAL_CIDADE VARCHAR(50) NOT NULL,
FILIAL_ESTADO VARCHAR(50) NOT NULL,
FILIAL_PAIS VARCHAR(50) NOT NULL,
FILIAL_CODPOSTAL VARCHAR(10) NOT NULL,
FILIAL_CAPACIDADE TEXT NOT NULL);

ALTER TABLE FILIAIS ADD TESTE TEXT;
ALTER TABLE FILIAIS DROP TESTE TEXT;

INSERT INTO FILIAIS (FILIAL_NOME, FILIAL_NUMRUA, FILIAL_BAIRRO)
VALUES ('Labirinto', '365', 'Praia da Costa');
INSERT INTO FILIAIS (FILIAL_NOME, FILIAL_NUMRUA, FILIAL_BAIRRO)
VALUES ('laringement', '366', 'itaparica');
INSERT INTO FILIAIS (FILIAL_NOME, FILIAL_NUMRUA, FILIAL_BAIRRO)
VALUES ('Larabio', '367', 'Praia da Costa');

#CRIANDO A TABELINHA PRODUTOS
CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_COD INT PRIMARY KEY,
PROD_NOME VARCHAR(50) NOT NULL,
PROD_DESCRICAO TEXT NOT NULL,
PROD_ESPECTEC TEXT NOT NULL,
PROD_QUANT DECIMAL(10,3) NOT NULL,
PROD_PRECOUNIT DECIMAL(10,2) NOT NULL,
PROD_UNIDMEDIDA VARCHAR(10) NOT NULL,
PROD_ESTOQ_MIN DECIMAL(10,3) NOT NULL
);

INSERT INTO PRODUTOS (PROD_QUANT, PROD_NOME, PROD_UNIDMEDIDA)
VALUES (5, 'Isac', 'Praia da Costa');
INSERT INTO PRODUTOS (PROD_QUANT, PROD_NOME, PROD_UNIDMEDIDA)
VALUES (6, 'Joao', 'itaparica');
INSERT INTO PRODUTOS (PROD_QUANT, PROD_NOME, PROD_UNIDMEDIDA)
VALUES (7, 'Maria', 'Praia da Costa');

#FASE 4: CRIAR AS TABELAS COM DEPENDÊNCIA DE CHAVE ESTRANGEIRA

#CRIANDO A TABELA PEDIDOS
CREATE TABLE IF NOT EXISTS PEDIDOS(
PED_CODIGO INT PRIMARY KEY,
PED_DATA DATE NOT NULL,
PED_HORA TIME NOT NULL,
PED_PREVISAO DATE NOT NULL,
PED_STATUS ENUM('PENDENTE','CONCLUÍDO','EM ESPERA'),
PED_FORNECEDOR INT NOT NULL, #NOSSA CHAVE ESTRANGEIRA DE FORNECEDOR
#CRIANDO A REFERENCIA PARA A CHAVE ESTRANGEIRA
#RESTRIÇÃO APELIDO CH.ESTRANGEIRA(CAMPO CRIADO) REFERENCIA TABELA(CH.PRIMÁRIA)
CONSTRAINT FK_FORNECEDOR FOREIGN KEY (PED_FORNECEDOR) #DAR NOME A RESTRIÇÃO(CONSTRAINT) É UMA BOA PRÁTICA
REFERENCES FORNECEDORES(FORNEC_COD) #REFERENCIA A CHAVE PRIMÁRIA DE FORNECEDORES
);

INSERT INTO PEDIDOS (PED_DATA, PED_HORA, PED_PREVISAO)
VALUES (5/5/2006, 18:52, 7/6/2007);
INSERT INTO PEDIDOS (PED_DATA, PED_HORA, PED_PREVISAO)
VALUES (6/5/2006, 18:51, 7/5/2007);
INSERT INTO PEDIDOS (PED_DATA, PED_HORA, PED_PREVISAO)
VALUES (7/5/2006, 18:50, 7/7/2007);

#CRIANDO A TABELA RECEBIMENTOS (VEIO DEPOIS POIS TEM DEPENDÊNCIA DE PEDIDOS)
CREATE TABLE IF NOT EXISTS RECEBIMENTOS(
RECEB_DATA DATE NOT NULL,
RECEB_HORA TIME NOT NULL,
RECEB_QUANT_PROD DECIMAL(10,3),
RECEB_CONDICAO TEXT NOT NULL,
RECEB_PEDIDOS INT PRIMARY KEY,
CONSTRAINT FK_PEDIDOS FOREIGN KEY(RECEB_PEDIDOS) REFERENCES PEDIDOS(PED_CODIGO));

INSERT INTO RECEBIMENTOS (RECEB_DATA, RECEB_HORA, RECEB_CONDICAO)
VALUES (5/5/2006, 18:52, 'Otima');
INSERT INTO RECEBIMENTOS (RECEB_DATA, RECEB_HORA, RECEB_CONDICAO)
VALUES (6/5/2006, 18:51, 'Otima');
INSERT INTO RECEBIMENTOS (RECEB_DATA, RECEB_HORA, RECEB_CONDICAO)
VALUES (7/5/2006, 18:50, 'Otima');


#FASE 5: CRIANDO AS TABELAS ASSOCIATIVAS (ENTIDADES ASSOCIATIVAS)

#CRIANDO A TABELA PEDIDOS_PRODUTOS
CREATE TABLE IF NOT EXISTS PEDIDOS_PRODUTOS(
PDPR_PEDIDOS INT,
PDPR_PRODUTOS INT,
PRIMARY KEY(PDPR_PEDIDOS,PDPR_PRODUTOS),
PDPR_QUANT DECIMAL(10,3) NOT NULL,
CONSTRAINT PDPR_FK_PEDIDOS FOREIGN KEY(PDPR_PEDIDOS) REFERENCES PEDIDOS(PED_CODIGO),
CONSTRAINT PDPR_FK_PRODUTOS FOREIGN KEY(PDPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD)
);

INSERT INTO PEDIDOS_PRODUTOS (PDPR_QUANT)
VALUES (72);
INSERT INTO PEDIDOS_PRODUTOS (PDPR_QUANT)
VALUES (65);
INSERT INTO PEDIDOS_PRODUTOS (PDPR_QUANT)
VALUES (54);

#CRIANDO A TABELA FILIAIS_PRODUTOS
CREATE TABLE IF NOT EXISTS FILIAIS_PRODUTOS(
FLPR_FILIAL INT,
FLPR_PRODUTOS INT,
PRIMARY KEY(FLPR_FILIAL,FLPR_PRODUTOS),
FLPR_QUANT DECIMAL(10,3) NOT NULL,
CONSTRAINT FLPR_FK_FILIAIS FOREIGN KEY(FLPR_FILIAL) REFERENCES FILIAIS(FILIAL_COD),
CONSTRAINT FLPR_FK_PRODUTOS FOREIGN KEY(FLPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD));

INSERT INTO FILIAIS_PRODUTOS (FLPR_QUANT)
VALUES (72);
INSERT INTO FILIAIS_PRODUTOS (FLPR_QUANT)
VALUES (65);
INSERT INTO FILIAIS_PRODUTOS (FLPR_QUANT)
VALUES (54);

#CRIAR A TABELA FORNECEDORES_PRODUTOS
CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS(
FRPR_FORNECEDOR INT,
FRPR_PRODUTOS INT,
PRIMARY KEY(FRPR_FORNECEDOR,FRPR_PRODUTOS),
CONSTRAINT FRPR_FK_FORNECEDORES FOREIGN KEY(FRPR_FORNECEDOR)
REFERENCES FORNECEDORES(FORNEC_COD),
CONSTRAINT FRPR_FK_PRODUTOS FOREIGN KEY(FRPR_PRODUTOS) 
REFERENCES PRODUTOS(PROD_COD));

DROP SCHEMA EC1_CC1M;
